name: build and run tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # install dependencies
    # name: boost
    #  run: sudo apt-get update && sudo apt-get install -yq libboost1.65-dev
    # build project
    - name: cd
      run: cd crashfix_service
    - name: generate cmake makefiles
      run: cmake -G "Unix Makefiles" 
    - name: make
      run: make
    # run tests    
    # - name: run test 1
    #  run: build/tst/Example1_tst
    # - name: run test 2
    #  run: build/tst/Example2_tst
